// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haxqkmqjmeoiduljepdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhheHFrbXFqbWVvaWR1bGplcGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTg0ODIsImV4cCI6MjA2OTk3NDQ4Mn0.rX5Ba4NgLRL5KOSZ_zWUXvU2C38nMUYTCLoMOcVg0Rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});