// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olyrpjlrnoxxhhomnqij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seXJwamxybm94eGhob21ucWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDQ1NjksImV4cCI6MjA3MjA4MDU2OX0.Gev3cnl2g6ntxzwJpN-LmPle5Uiu2eNkKBNtiuTbKVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});